
<hgroup>

  <h1>Reset Password</h1>

  <h2>Type Your New Password Below</h2>

</hgroup>

<p>Your password should contain at least six characters and should contain both letters and numbers for extra security.</p>

<form id="reset-password-form" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post" class="generic">

  <fieldset>

    <dl>
      <dt><label for="username">Your Username:</label> (cannot be changed here)</dt>
      <dd><input id="username" type="text" name="username" autocomplete="off" readonly="readonly" value="<?php echo $this->escape($this->objUser->username); ?>" /></dd>

      <dt><label for="username">Email Address:</label> (cannot be changed here)</dt>
      <dd><input id="username" type="email" name="username" autocomplete="off" readonly="readonly" value="<?php echo $this->escape($this->objUser->username); ?>" required="required" /></dd>

      <dt><label for="password">Your New Password:</label> (at least 6 characters)</dt>
      <dd><input id="password" type="password" name="password" autocomplete="off" required="required" /></dd>
    
      <dt><label for="password_confirmation">Confirm Your New Password:</label></dt>
      <dd><input id="password_confirmation" type="password" name="password_confirmation" autocomplete="off" required="required" /></dd>
    </dl>

  </fieldset>

  <fieldset class="submit">

    <input type="submit" value="Submit" />

  </fieldset>

</form>
