
<!-- See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination -->

<?php if ($this->pageCount): ?>

<p class="paginator">

<?php $strQueryString = ($_SERVER['QUERY_STRING'] != '') ? $this->escape('?' . $_SERVER['QUERY_STRING']) : ''; ?>

  <!-- Previous Page Link -->

<?php if (isset($this->previous)): ?>
  <a href="<?php echo str_replace('//', '/', $this->url(array('page' => $this->previous))) . $strQueryString ; ?>">&lt; Previous</a> | 
<?php else: ?>
  <span class="disabled">&lt; Previous</span> | 
<?php endif; ?>

  <!-- Numbered Page Links -->

<?php foreach ($this->pagesInRange as $page): ?>
<?php if ($page != $this->current): ?>
  <a href="<?php echo str_replace('//', '/', $this->url(array('page' => $page))) . $strQueryString ; ?>"><?php echo $page; ?></a> | 
<?php else: ?>
  <?php echo $page; ?> | 
<?php endif; ?>
<?php endforeach; ?>

  <!-- Next Page Link -->

<?php if (isset($this->next)): ?>
  <a href="<?php echo str_replace('//', '/', $this->url(array('page' => $this->next))) . $strQueryString ; ?>">Next &gt;</a>
<?php else: ?>
  <span class="disabled">Next &gt;</span>
<?php endif; ?>

</p>

<?php endif; ?>
