
<h1>Users</h1>

<p>This page displays all of the registered users of the Love Week site. <a href="/admin/users/manage">+ Add a new user</a></p>

<?php echo $this->paginationControl($this->objPaginator, 'sliding', 'partials/paginator/displaying.phtml'); ?>

<form method="get">

  <fieldset>

    <div class="row search">
      <div class="col-sm-6 field"><input type="text" name="keywords" value="<?php echo $this->escape($this->strKeywords); ?>" /></div>
      <div class="col-sm-6 button"><input type="submit" value="Search" class="btn btn-primary" /></div>
    </div>

    <div class="table-responsive">

      <table class="table table-striped table-sort">

        <thead>
          <tr>
            <th><!-- Edit | Del --></th>
      <?php foreach($this->arrFields as $strField): ?>
            <th <?php echo ($strField == 'Last name') ? 'class="tablesorter-headerAsc"' : ''; ?>><?php echo $strField; ?></th>
      <?php endforeach; ?>
          </tr>
        </thead>

        <tbody>
      <?php foreach ($this->objPaginator as $arrRow): ?>
      <?php $objUser = (object) $arrRow; ?>
          <tr>
            <td><a href="/admin/users/manage/id/<?php echo $objUser->id; ?>">Edit</a> | <a href="/admin/users/delete/id/<?php echo $objUser->id; ?>">Del</a></td>
            <td><?php echo $objUser->user_last_name; ?></td>
            <td><?php echo $objUser->user_first_name; ?></td>
            <td><?php echo $objUser->username; ?></td>
            <td><?php echo $objUser->user_phone; ?></td>
            <td><?php echo ($objUser->user_is_admin) ? 'Yes' : 'No'; ?></td>
            <td><?php echo ($objUser->user_is_active) ? 'Yes' : 'No'; ?></td>
          </tr>
      <?php endforeach; ?>
        </tbody>

      </table>

    </div>

    <?php echo $this->paginationControl($this->objPaginator); ?>

  </fieldset>

</form>