
<h1><?php echo $this->strPrimary; ?></h1>

<ul>
  <li style="font-family: 'titillium-thin'">Titillium Thin</li>
  <li style="font-family: 'titillium-light'">Titillium Light</li>
  <li style="font-family: 'titillium-regular'">Titillium Regular</li>
  <li style="font-family: 'titillium-semibold'">Titillium Semibold</li>
  <li style="font-family: 'titillium-bold'">Titillium Bold</li>
  <li style="font-family: 'titillium-black'">Titillium Black</li>
</ul>